# Generated by Django 5.1.6 on 2025-03-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10)),
                ('confederation', models.CharField(choices=[('league_men', 'Besta deild karl'), ('league_women', 'Besta deild kvenna'), ('cup_men', 'Mjólkurbikar karla'), ('cup_women', 'Mjólkurbikar kvenna'), ('europe_men', 'Evrópa karla'), ('europe_women', 'Evrópa kvenna'), ('friendly_men', 'Vináttuleikur karla'), ('friendly_women', 'Vináttuleikur kvenna')], default='Besta deildin', max_length=20)),
                ('played', models.BooleanField(default=False)),
                ('home_goals', models.IntegerField(default=0)),
                ('away_goals', models.IntegerField(default=0)),
                ('home_formation', models.CharField(choices=[('3-4-1-2', '3-4-1-2'), ('3-1-4-2', '3-1-4-2'), ('3-4-2-1', '3-4-2-1'), ('3-4-3', '3-4-3'), ('3-5-1-1', '3-5-1-1'), ('3-5-2', '3-5-2'), ('4-1-2-1-2', '4-1-2-1-2'), ('4-1-2-3', '4-1-2-3'), ('4-1-3-2', '4-1-3-2'), ('4-1-4-1', '4-1-4-1'), ('4-2-1-3', '4-2-1-3'), ('4-2-2-2', '4-2-2-2'), ('4-2-3-1', '4-2-3-1'), ('4-2-4', '4-2-4'), ('4-3-1-2', '4-3-1-2'), ('4-3-2-1', '4-3-2-1'), ('4-3-3', '4-3-3'), ('4-4-1-1', '4-4-1-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('5-2-1-2', '5-2-1-2'), ('5-2-2-1', '5-2-2-1'), ('5-2-3', '5-2-3'), ('5-3-2', '5-3-2'), ('5-4-1', '5-4-1')], default='4-4-2', max_length=10)),
                ('away_formation', models.CharField(choices=[('3-4-1-2', '3-4-1-2'), ('3-1-4-2', '3-1-4-2'), ('3-4-2-1', '3-4-2-1'), ('3-4-3', '3-4-3'), ('3-5-1-1', '3-5-1-1'), ('3-5-2', '3-5-2'), ('4-1-2-1-2', '4-1-2-1-2'), ('4-1-2-3', '4-1-2-3'), ('4-1-3-2', '4-1-3-2'), ('4-1-4-1', '4-1-4-1'), ('4-2-1-3', '4-2-1-3'), ('4-2-2-2', '4-2-2-2'), ('4-2-3-1', '4-2-3-1'), ('4-2-4', '4-2-4'), ('4-3-1-2', '4-3-1-2'), ('4-3-2-1', '4-3-2-1'), ('4-3-3', '4-3-3'), ('4-4-1-1', '4-4-1-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('5-2-1-2', '5-2-1-2'), ('5-2-2-1', '5-2-2-1'), ('5-2-3', '5-2-3'), ('5-3-2', '5-3-2'), ('5-4-1', '5-4-1')], default='4-4-2', max_length=10)),
                ('home_yellow_cards', models.IntegerField(default=0)),
                ('away_yellow_cards', models.IntegerField(default=0)),
                ('home_red_cards', models.IntegerField(default=0)),
                ('away_red_cards', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_number', models.IntegerField(primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField()),
                ('home_score', models.CharField(blank=True, max_length=10, null=True)),
                ('away_score', models.CharField(blank=True, max_length=10, null=True)),
                ('stadium_name', models.CharField(max_length=255)),
                ('stadium_number', models.IntegerField()),
                ('attendance', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_number', models.IntegerField(default='123', primary_key=True, serialize=False)),
                ('name', models.CharField(default='debug needed', max_length=255)),
                ('birth_year', models.CharField(default='0123', max_length=4)),
                ('first_team_matches', models.IntegerField(default=0)),
                ('first_team_goals', models.IntegerField(default=0)),
                ('national_team_matches', models.IntegerField(default=0)),
                ('national_team_goals', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('GK', 'Markmaður'), ('DEF', 'Varnarmaður'), ('MID', 'Miðjumaður'), ('FW', 'Sóknarmaður')], max_length=3)),
                ('secondary_position', models.CharField(blank=True, choices=[('GK', 'Markmaður'), ('DEF', 'Varnarmaður'), ('MID', 'Miðjumaður'), ('FW', 'Sóknarmaður')], max_length=3, null=True)),
                ('third_position', models.CharField(blank=True, choices=[('GK', 'Markmaður'), ('DEF', 'Varnarmaður'), ('MID', 'Miðjumaður'), ('FW', 'Sóknarmaður')], max_length=3, null=True)),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_number', models.IntegerField(default='123', primary_key=True, serialize=False)),
                ('name', models.CharField(default='debug needed', max_length=255)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('default_formation', models.CharField(choices=[('3-4-1-2', '3-4-1-2'), ('3-1-4-2', '3-1-4-2'), ('3-4-2-1', '3-4-2-1'), ('3-4-3', '3-4-3'), ('3-5-1-1', '3-5-1-1'), ('3-5-2', '3-5-2'), ('4-1-2-1-2', '4-1-2-1-2'), ('4-1-2-3', '4-1-2-3'), ('4-1-3-2', '4-1-3-2'), ('4-1-4-1', '4-1-4-1'), ('4-2-1-3', '4-2-1-3'), ('4-2-2-2', '4-2-2-2'), ('4-2-3-1', '4-2-3-1'), ('4-2-4', '4-2-4'), ('4-3-1-2', '4-3-1-2'), ('4-3-2-1', '4-3-2-1'), ('4-3-3', '4-3-3'), ('4-4-1-1', '4-4-1-1'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('5-2-1-2', '5-2-1-2'), ('5-2-2-1', '5-2-2-1'), ('5-2-3', '5-2-3'), ('5-3-2', '5-3-2'), ('5-4-1', '5-4-1')], default='4-4-2', max_length=10)),
                ('goal_song', models.FileField(blank=True, null=True, upload_to='goal_songs/')),
                ('default_lineup_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='debug need', max_length=255)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_announcement', models.TextField(default="Welcome to today's match!")),
                ('halftime_announcement', models.TextField(default="It's halftime. Get your snacks!")),
                ('fulltime_announcement', models.TextField(default='Full-time. Thank you for coming!')),
                ('goal_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('sponsor_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gameday', to='matches.game')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(default='0')),
                ('event_type', models.CharField(max_length=255)),
                ('event_number', models.IntegerField(default=1)),
                ('match', models.ForeignKey(default='debug needed', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(default='debug needed', on_delete=django.db.models.deletion.CASCADE, to='matches.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team'),
        ),
        migrations.CreateModel(
            name='GameLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Markmaður'), ('DEF', 'Varnarmaður'), ('MID', 'Miðjumaður'), ('FW', 'Sóknarmaður')], max_length=3)),
                ('position_number', models.IntegerField(default=0)),
                ('order', models.CharField(blank=True, choices=[('1', 'GK'), ('2', 'RB'), ('3', 'LB'), ('4', 'LCB'), ('5', 'RCB'), ('6', 'CB'), ('7', 'LWB'), ('8', 'RWB'), ('9', 'CM'), ('10', 'LCM'), ('11', 'RCM'), ('12', 'LDM'), ('13', 'RDM'), ('14', 'AM'), ('15', 'RAM'), ('16', 'LAM'), ('17', 'LM'), ('18', 'RM'), ('19', 'LW'), ('20', 'RW'), ('21', 'CF'), ('22', 'LST'), ('23', 'RST'), ('24', 'ST')], max_length=24, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.team')),
            ],
            options={
                'ordering': ['position_number'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='matches.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tournament'),
        ),
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_drawn', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
                ('points', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
