# Generated by Django 5.1.6 on 2025-03-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_tournament_start_date_gamedayjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTournamentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_tournament', models.BooleanField(default=False, help_text='Is this a main tournament for this team?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_filters', to='matches.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.tournament')),
            ],
            options={
                'verbose_name': 'Team Tournament Filter',
                'verbose_name_plural': 'Team Tournament Filters',
                'unique_together': {('team', 'tournament')},
            },
        ),
    ]
