# Generated by Django 5.1.6 on 2025-03-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_teamtournamentfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_to_users', models.BooleanField(default=True, help_text='If checked, this team will be shown in team selection dropdowns')),
                ('display_priority', models.PositiveIntegerField(default=100, help_text='Lower numbers appear first in selection lists')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='matches.team')),
            ],
            options={
                'verbose_name': 'Team Visibility Setting',
                'verbose_name_plural': 'Team Visibility Settings',
                'ordering': ['display_priority', 'team__name'],
            },
        ),
    ]
